server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

eureka:
  instance:
    instance-id: payment8001
    #    访问路径是否显示IP
    prefer-ip-address: true
    #    发送心跳间隔 默认是30s
    lease-renewal-interval-in-seconds: 1
    #    服务端在收到最后一次心跳之后的等待时间 默认是90s，超时剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    #向注册中心注册自己
    register-with-eureka: true
    # false表示自己端就是注册中心,我的职贡就是维护服务实例,并不需要去检索服务 否则亦然
    fetch-registry: true
    #设置与 Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.yy.cloud.entitiesk











