#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80


#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-comsumer-order-zk
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181



